[env]
TERM = "xterm-256color"

[terminal]
shell.program = "/usr/bin/fish"
shell.args = ["-l"]

[window]
padding.x = 10
padding.y = 10
opacity = 0.95

[font]
normal.family = "CommitMono Nerd Font Mono"
size = 12

[general]
import = ["~/.config/alacritty/themes/github-dark-colorblind.toml"]
